version: "3.9"

services:
  app:
    build: .
    image: ghcr.io/otlet/pocketbase:latest
    ports:
      - "8090:8090"
    volumes:
      - ./data:/usr/local/lib/pb/data
      - ./migration:/usr/local/lib/pb/migration
      - ./public:/usr/local/lib/pb/public
